# =============================================================================
# Production Profile
# =============================================================================

# Database
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
app.base-url=${APP_BASE_URL}
frontend.base-url=${FRONTEND_BASE_URL}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false



# Stripe
stripe.secret-key=${STRIPE_SECRET_KEY}